% define_guid.m 
%   Define guidance data structure
%
% Aeroassist Simulation (asim) Source Code
%
% Original version developed by M. J. Grant, Z. R. Putnam
%   Space Systems Design Lab
%   Georgia Institute of Technology
%
% Maintained by Putnam Research Group
%   Department of Aerospace Engineering
%   University of Illinois at Urbana-Champaign
%
% Input:
%   none
%   
% Output:
%   guid - struct(1), multi, guidance data structure

function guid = define_guid()
%#codegen

%% Command data structure
cmd = struct( ...
    'deploy_decel', logical(false), ...
    'aoa', double(0), ...
    'aoa_rate', double(0), ...
    'bank', double(0), ...    
    'bank_rate', double(0), ...
    't_jettison', double(0), ...
    'area_ref', double(0) );

%% Parameter data structure
p = struct( ...
    'aoa_mode', uint8(0), ...
    'bank_mode', uint8(0), ...
    'prop_mode', uint8(0), ...
    'rate', double(0), ...
    'tgt_lat', double(0), ...
    'tgt_lon', double(0), ...
    'const_aoa', double(0), ...
    'const_bank',double(0), ...
    'const_bank_rate',double(0),...
    'aoa_schedule', double(zeros(100,2)),...
    'aoa_sched_len', double(0),...
    'bank_schedule',double(zeros(100,2)),...
    'bank_sched_len',double(0) );
    
%% State data structure
s = struct( ...
    'init_flag',logical(false), ...    
    'sg_ratio', double(0) );

%% Algorithm-specific data structures
msl = define_g_msl; % MSL-prime entry guidance
sej_a = define_g_sej_a; % Single-event-jettison aerocapture guidance (drag modulation)
sej_e = define_g_sej_e; % Single-event-jettison entry guidance (drag modulation)
dma_cv = define_g_dma_cv; % Aerocapture drag modulation: continuously variable
gt = define_g_gt; % Gravity turn terminal descent guidance

%% Construct combined data structure
guid = struct( ...
    'cmd', cmd, ...
    'p', p, ...
    's', s, ...
    'msl', msl, ...
    'sej_a', sej_a, ...
    'dma_cv', dma_cv, ...
    'sej_e', sej_e, ...
    'gt', gt ...
    );

end % define_guid()
