% define_ctrl.m 
%   Define flight control data structure.
%
% Aeroassist Simulation (asim) Source Code
%
% Original version developed by M. J. Grant, Z. R. Putnam
%   Space Systems Design Lab
%   Georgia Institute of Technology
%
% Maintained by Putnam Research Group
%   Department of Aerospace Engineering
%   University of Illinois at Urbana-Champaign
%
% Input:
%   none
%   
% Output:
%   ctrl - struct(1), multi, control data structure

function ctrl = define_ctrl()
%#codegen

%% Parameter data structure
p = struct( ...
    'aoa_mode', uint8(0), ...
    'bank_mode', uint8(0), ...
    'decel_mode', uint8(0), ...
    'rate', double(0), ...
    'aoa_rate_lim', double(0), ...
    'aoa_accel_lim', double(0), ...    
    'bank_rate_lim', double(0), ...
    'bank_accel_lim', double(0), ...
    'bank_accel_lim1', double(0), ...
    'bank_accel_lim2', double(0), ...
    'bank_accel_dynp1', double(0), ...
    'bank_accel_dynp2', double(0), ...
    'decel_v_box', double(zeros(2,1)));

%% State data structure
s = struct( ...
    'ignition', logical(false), ...
    'jettison', logical(false), ...
    'not_jettisoned', logical(false), ...
    'deploy_decel', logical(false), ...
    'sc_ratio', double(0), ...        
    't_ini', double(0), ...    
    't_prev', double(0), ...
    't', double(0), ...
    'dt', double(0), ...
    'area_ref', double(0), ...
    'aoa_accel', double(0), ...        
    'aoa_rate', double(0), ...    
    'aoa', double(0), ...   
    'bank_accel', double(0), ...        
    'bank_rate', double(0), ...    
    'bank', double(0) );
     
%% Construct combined input data structure
ctrl = struct( ...
    's', s, ...
    'p', p );

end % define_ctrl()
