% define_nav.m 
%   Define navigation data structure.
%
% Aeroassist Simulation (asim) Source Code
%
% Original version developed by M. J. Grant, Z. R. Putnam
%   Space Systems Design Lab
%   Georgia Institute of Technology
%
% Maintained by Putnam Research Group
%   Department of Aerospace Engineering
%   University of Illinois at Urbana-Champaign
%
% Input:
%   none
%   
% Outputs:
%   nav - struct(1), multi, navigation data structure

function nav = define_nav()
%#codegen

%% Parameter data structure
p = struct( ...
    'mode', uint8(0), ...
    'seed', uint32(0), ...
    'rate', double(0), ...
    'tau', double(0), ...
    'r_e', double(0), ...
    'r_p', double(0), ...
    'omega', double(zeros(3,1)), ...
    'P_SS', double(zeros(9)) );

%% State data structure
s = struct( ...
    'r_pci', double(zeros(3,1)), ...
    'r_pcpf', double(zeros(3,1)), ...
    'v_inrtl_pci', double(zeros(3,1)), ...
    'v_pf_pci', double(zeros(3,1)), ...
    'v_pf_pcpf', double(zeros(3,1)), ...
    'a_sens_pci', double(zeros(3,1)), ...
    'a_sens_pcpf', double(zeros(3,1)), ...
    'lat_gd', double(0), ...
    'lon', double(0), ...
    'alt', double(0), ...
    'dt', double(0), ...
    'sn_ratio', double(0), ...
    't', double(0), ...
    't_ini', double(0), ...
    'x_ercv', double(zeros(9,1)), ...
    'rva_error', double(zeros(9,1)) );
     
%% Construct combined input data structure
nav = struct( ...
    's', s, ...
    'p', p );

end % define_nav()
